CREATE DATABASE HISTORIA_ESPACIAL;

-- CREACIÓN DE LA TABLA COHETES --
CREATE TABLE COHETE (
  ID_COHETE INT,
  NOMBRE VARCHAR(255),
  FABRICANTE VARCHAR(255),
  VUELO DATE,
  PAIS VARCHAR(255),
  PRIMARY KEY (ID_COHETE)
);

-- CREACIÓN DE LA TABLA CONFIGURACIÓN DEL COHETE --
CREATE TABLE CONFIGURACIONCOHETE (
  ID_CONFIGURACION INT,
  ID_COHETE INT,
  NOMBRE VARCHAR(255),
  MOTOR VARCHAR(255),
  MASA_CARGA DECIMAL,
  PRIMARY KEY (ID_CONFIGURACION),
  FOREIGN KEY (ID_COHETE) REFERENCES Cohete(ID_COHETE)
);

-- CREACIÓN DE LA TABLA ETAPAS DEL COHETE --
CREATE TABLE ETAPASCOHETE (
  ID_ETAPA INT ,
  ID_CONFIGURACION INT,
  NOMBRE VARCHAR(255),
  MOTOR VARCHAR(255),
  NUMERO_ETAPA INT,
  COMBUSTIBLE VARCHAR(255),
  PRIMARY KEY (ID),
  FOREIGN KEY (ID_CONFIGURACION) REFERENCES CONFIGURACIONCOHETE(ID_CONFIGURACION)
);

-- CREACIÓN DE LA TABLA CARGA DE PAGO --
CREATE TABLE CARGAPAGO (
  ID_CARGA INT ,
  ID_COHETE INT,
  NOMBRE VARCHAR(255),
  TIPO VARCHAR(255),
  MASA DECIMAL,
  PRIMARY KEY (ID_CARGA),
  FOREIGN KEY (ID_COHETE) REFERENCES COHETE(ID_COHETE)
);

-- CREACIÓN DE LA TABLA LANZAMIENTO --
CREATE TABLE LANZAMIENTO (
  ID_LANZAMIENTO INT ,
  ID_COHETE INT,
  FECHA DATE,
  LUGAR VARCHAR(255),
  EXITO BOOLEAN,
  ORBITA VARCHAR(255),
  PRIMARY KEY (ID_LANZAMIENTO),
  FOREIGN KEY (ID_COHETE) REFERENCES Cohete(ID_COHETE)
);